### ISSUE TITLE
Umgang mit dem "Feature-Bild"

### ISSUE THREAD

**Issue by justinotherguy** [section77/website#13]
Derzeit tragen wir händisch ein "Feature-Bild" ein; dieses wird auf der Seite angezeigt.

Vorschlag:
- es existiert ein default-Feature-Bild
- dieses lässt sich - temporär - überschreiben mit einem Feature für ein Event

-> Beispiel:
- EggBot-Event am 2018-03-03; expiry: 2018-03-03+1
- Default: $DEFAULT-Bild

-> so haben wir keine veralteten Bilder mehr auf der Einstiegsseite, auch wenn wir vergessen, es zu aktualisieren

Gruß, J.

**Comment by paepke** [comment]
klingt gut mit dem feature bild.
Ich hab sowieso mal drueber nachgedacht die Events mit nem zusätzlichen Bild zu versorgen. So können wir ein hübscheres Event Listing erreichen und eben laut deinem Vorschlage das nächste Event besser Featuren.

**Comment by justinotherguy** [comment]
@paepke hast Du das noch auf dem Zettel oder sollen wir das zu machen?

**Comment by paepke** [comment]
hab ich noch aufm schirm
