### ISSUE TITLE
Broken links (checked by linkchecker)

### ISSUE THREAD

**Issue by sysdef** [section77/website#39]
LinkChecker 10.0.1

Start checking at 2021-11-14 17:32:47+002

URL        '../media/20141115_194913.3gp'
Name       '3gp'
Parent URL https://section77.de/projects/, line 103, col 2
Real URL   https://section77.de/media/20141115_194913.3gp
Check time 3.913 seconds
Size       5KB
Result     Error: 404 Not Found

URL        '../media/20141115_194913.mp4'
Name       'mp4'
Parent URL https://section77.de/projects/, line 104, col 3
Real URL   https://section77.de/media/20141115_194913.mp4
Check time 3.699 seconds
Size       5KB
Result     Error: 404 Not Found

URL        '../media/20141115_194913.ogv'
Name       'ogv'
Parent URL https://section77.de/projects/, line 105, col 3
Real URL   https://section77.de/media/20141115_194913.ogv
Check time 3.891 seconds
Size       5KB
Result     Error: 404 Not Found

URL        '../media/20141115_194913.webm'
Name       'webm'
Parent URL https://section77.de/projects/, line 106, col 3
Real URL   https://section77.de/media/20141115_194913.webm
Check time 3.872 secondsa
Size       5KB
Result     Error: 404 Not Found

URL        './2019-01-05/slides.pdf'
Name       'Slides'
Parent URL https://section77.de/kalender/2019/page/4/, line 193, col 4
Real URL   https://section77.de/kalender/2019/page/4/2019-01-05/slides.pdf
Check time 1.612 seconds
Size       5KB
Result     Error: 404 Not Found

Statistics:
Downloaded: 507.63KB.
Content types: 8 image, 36 text, 0 video, 0 audio, 6 application, 1 mail and 53 other.
URL lengths: min=20, max=77, avg=44.

That's it. 104 links in 104 URLs checked. 0 warnings found. 5 errors found.
Stopped checking at 2021-11-14 17:33:08+002 (21 seconds)

**Comment by justinotherguy** [comment]
Interesting - thank you!
I suppose, the video (1 video in 3 formats) is lost :/
We'll look into that - maybe...

The slides is a different case, though: the file itself exists (https://section77.de/kalender/2019//2019-01-05/slides.pdf); and when it was shown in the "overview" to "standard view" (https://section77.de/kalender/ -> "Nächste Termine") the link was working, too. But when you have to step back in time the parent URL changes (https://section77.de/kalender/ -> https://section77.de/kalender/2019/page/4/); and that breaks it.

@j-keck any idea, how be can solve this?

We could use absolute paths for attachments (actually this is the only one we have so far). That would work in both cases, wouldn't it?

So, the change would be:
old (broken): ./2019-01-05/slides.pdf
new (fixed): /kalender/2019/2019-01-05/slides.pdf

What do you think, @j-keck ?

Regards, J.

**Comment by sysdef** [comment]
found the lost mp3 video in archive.org .  
converted to webm, ogv and 3gp
